[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
